apiVersion: v1
kind: Secret
metadata:
  name: seafile-secrets
  namespace: seafile
type: Opaque
stringData:
  mysql-root-password: "db_root_password"
  seafile-admin-email: "admin@seafile.local"
  seafile-admin-password: "admin_password"
